version: '3'
services:
  app:
    image: "novaintrospection/nova-prod"
    container_name: "nova-prod"
    ports: 
    - "3000:3000"
    volumes:
    - ./:/usr/src/app
    - node_modules:/usr/src/app/node_modules
    depends_on: 
    - redis
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: ["redis-server"]
volumes: 
  node_modules: {}